server:
  port: 80
mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
#  type-aliases-package: cn.mldn.microboot.vo            # 定义所有操作类的别名所在包
  mapperLocations : classpath*:**/*SqlMap.xml
  check-config-location: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

spring:
  messages:
    basename: i18n/Messages,i18n/Pages
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.jdbc.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/o2o_db?useSSL=true&serverTimezone=UTC           # 数据库连接地址
    username: root                                  # 数据库用户名
    password: 123456                            # 数据库连接密码
    filters: stat,wall,log4j
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  freemarker:
    #关闭缓存
    cache: false
    request-context-attribute: request
    #模板加载的位置
    template-loader-path: classpath:/templates/
    suffix: .ftl
    check-template-location: true

config:
  datasource:
    datasource1:
      url: jdbc:mysql://localhost:3306/o2o_db?useSSL=true&serverTimezone=UTC           # 数据库连接地址
      username: root                                  # 数据库用户名
      password: 123456
    datasource2:
      url: jdbc:mysql://localhost:3306/o2o_db?useSSL=true&serverTimezone=UTC           # 数据库连接地址
      username: root                                  # 数据库用户名
      password: 123456




